# Numpy

Numpy is a library for representing and working with large and multi-dimensional arrays. Most other libraries in the data-science ecosystem depend on numpy, making it one of the fundamental data science libraries.

Numpy provides a number of useful tools for scientific programming, and in this lesson, we'll take a look at some of the most common.

Convention is to import the `numpy` module as `np`.

In [6]:
import numpy as np

## Indexing

Numpy provides an array type that goes above and beyond what Python's built-in lists can do.

We can create a numpy array by passing a list to the `np.array` function:

In [7]:
a = np.array([1, 2, 3])

In [8]:
a

array([1, 2, 3])

In [9]:
print(a)

[1 2 3]


We can create a multi-dimensional array by passing a list of lists to the `array` function

In [10]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [11]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Referencing elements in numpy arrays at it's most basic is the same as referencing elements in Python lists.

In [13]:
a[0]

1

In [14]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [15]:
print('matrix')
print(matrix)
print('\n')
print('matrix[0] == {}'.format(matrix[0]))
print('matrix[1] == {}'.format(matrix[1]))
print('matrix[2] == {}'.format(matrix[2]))

matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix[0] == [1 2 3]
matrix[1] == [4 5 6]
matrix[2] == [7 8 9]


Multidimensional numpy arrays are easier to index into than nested lists. To obtain the element at the second column in the second row, we would write:

In [16]:
matrix[1,1]

5

To get the first 2 elements of the last 2 rows:

In [17]:
matrix[1:, :2] 
# 1: Give me the rows starting from index position 1 onward
# :2 Give me the elements of the rows up to *but not including* index position 2

array([[4, 5],
       [7, 8]])

Arrays can also be indexed with a boolean sequence used to indicate which values should be included in the resulting array.

In [18]:
a

array([1, 2, 3])

In [ ]:
a[[True, False, True]]

In [19]:
#You can save these boolean values to a 'boolean mass' which can then be called for use later, which can be very powerful.

should_include_elements_a = [True, False, True]
a[should_include_elements_a]

array([1, 3])

## Vectorized Operations

Another useful feature of numpy arrays is vectorized operations.

If we wanted to add 1 to every element in a list, without numpy, we can't simply add 1 to the list, as that will result in a `TypeError`.

In [1]:
#When looking at the below, keep in mind that this is a *list* not a numpy array.
original_array = [1, 2, 3, 4, 5]
try:
    original_array + 1
except TypeError as e:
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [2]:
# What does "can only concatenate list (not "int") to list" mean?
[1, 2, 3, 4, 5] + [1]

[1, 2, 3, 4, 5, 1]

We could write a `for` loop or a list comprehension:

In [3]:
#Here, again, the original array has been converted to a list in order to demonstrate how this could be done with a 'for' loop:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n+1)
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [4]:
#The above can similarly be done with a list comprehension, but the underlying process is the same and therefore still more intensive than a numpy array operation. 
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
print(array_with_one_added)

[2, 3, 4, 5, 6]


Vectorizing operations means that operations are automatically applied to every element in a vector, which in our case will be a numpy array. So if we are working with a numpy array, we can simply add 1:

In [21]:
#if we convert this array into a numpy array, then we can make use of the library's pre-built tools and complete this operation with similar syntax that wouldn't have worked in vanilla Python
numpy_array = np.array([1, 2, 3, 4, 5])
numpy_array + 1

array([2, 3, 4, 5, 6])

In [23]:
print(numpy_array + 2)

[3 4 5 6 7]


This works the same way for the other basic arithmetic operators as well:

In [24]:
my_array = np.array([-3, 0, 3, 16])

print(f'my_array      == {my_array}')
print(f'my_array - 5  == {my_array - 5}')
print(f'my_array * 4  == {my_array * 4}')
print(f'my_array / 2  == {my_array / 2}')
print(f'my_array ** 2 == {my_array ** 2}')
print(f'my_array % 2  == {my_array % 2}')

my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


Not only are the arithmatic operators vectorized, but the same applies to the comparison operators.

In [25]:
#I need to come back through here and look at these format strings.
my_array = np.array([-3, 0, 3, 16])

print(f'my_array       == {my_array}')
print(f'my_array == -3 == {my_array == -3}')
print(f'my_array >= 0  == {my_array >= 0}')
print(f'my_array < 10  == {my_array < 10}')

my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


If vectorizing a comparison operator produces a boolean array...

In [26]:
print(my_array > 0)

[False False  True  True]


And if we can give an array some booleans to select the values we want to return...

In [27]:
my_array[[False, False, True, True]]

array([ 3, 16])

Then we can "give" an array a condition to select our values for us!

In [31]:
# Give me all the positive numbers in my_array:
my_array[my_array > 0]

[-3  0  3 16]


array([ 3, 16])

## In-Depth Example
As another example, we could obtain all the even numbers like this:

In [32]:
print(my_array)
my_array[my_array % 2 == 0]

[-3  0  3 16]


array([ 0, 16])

To better understand how this is all working let's go through this recent example in a little more detail.

The first expression that gets evaluated is this:

In [30]:
my_array % 2

array([1, 0, 1, 0])

Which results in an array of `1`s and `0`s. Then the array of `1`s and `0`s is compared to `0` with the `==` operator, producing an array of `True` or `False` values.

In [34]:
# Each element of the array % 2
result = my_array % 2
print(f"My Array:              {my_array}")
print(f"My Array % 2 (Result): {result}")

My Array:              [-3  0  3 16]
My Array % 2 (Result): [1 0 1 0]


In [35]:
# Does each element % 2 == 0?
print(f"My Array:                   {my_array}")
print(f"My Array % 2 (Result):      {result}")
print(f"result == 0:                {result == 0}")

My Array:                   [-3  0  3 16]
My Array % 2 (Result):      [1 0 1 0]
result == 0:                [False  True False  True]


Lastly, we use this array of boolean values to index into the original array, which gives us only the values that are evenly divisible by 2.

In [36]:
step_1 = my_array % 2
step_2 = step_1 == 0
step_3 = my_array[step_2]

step_3

array([ 0, 16])

Put another way, here is how the expression is evaluated:

In [37]:
print('1. my_array[my_array % 2 == 0]')
print('    - the original expression')
print('2. my_array[{} % 2 == 0]'.format(my_array))
print('    - variable substitution')
print('3. my_array[{} == 0]'.format(my_array % 2))
print('    - result of performing the vectorized modulus 2')
print('4. my_array[{}]'.format(my_array % 2 == 0))
print('    - result of comparing to 0')
print('5. {}[{}]'.format(my_array, my_array % 2 == 0))
print('    - variable substitution')
print('6. {}'.format(my_array[my_array % 2 == 0]))
print('    - our final result')

1. my_array[my_array % 2 == 0]
    - the original expression
2. my_array[[-3  0  3 16] % 2 == 0]
    - variable substitution
3. my_array[[1 0 1 0] == 0]
    - result of performing the vectorized modulus 2
4. my_array[[False  True False  True]]
    - result of comparing to 0
5. [-3  0  3 16][[False  True False  True]]
    - variable substitution
6. [ 0 16]
    - our final result


In [38]:
# I want to find element >= 0 AND element < 0
my_array[(my_array >= 0) & (my_array < 10)]

array([0, 3])

In [40]:
# I want to find element >= 0 OR element < 0
my_array[(my_array < 0) | (my_array > 3)]

array([-3, 16])

In [41]:
len(my_array)

4

## Array Creation

Numpy provides several methods for creating arrays, we'll take a look at several of them.

### `np.random.randn`

`np.random.randn` can be used to create an array of specified length of random numbers drawn from the standard normal distribution.

> **Standard Normal Distribution**: Values range from -∞ to ∞ with equal distribution in both positive and negative direction, the mean is equal to 0, and the standard deviation is 1. The values represent z-scores, which are the number of standard deviations that point is from the mean.

In [42]:
np.random.randn(10)

array([-0.3776515 ,  0.38889961,  0.18490092, -0.76494464, -0.36875983,
       -1.59575827,  0.7919503 , -1.89781239, -0.20037438,  0.2427981 ])

We can also pass a second argument to this function to define the shape of a two dimensional array.

In [43]:
np.random.randn(3, 4) # rows, columns

array([[-2.76704507,  1.05233469, -1.28346285,  0.21064447],
       [ 1.45700002,  0.44617194, -1.3914791 ,  0.5485002 ],
       [-0.6136086 , -0.37343697, -0.83707477,  0.59044624]])

If we wish to obtain original values from the z-scores of a normal distribution, we'll need to apply some arithmetic. 

To convert, we'll need to multiply by the standard deviation (*σ*) and add the mean (*μ*).

In [44]:
z_scores_iq = np.random.randn(20)
z_scores_iq

array([ 1.21517075, -1.68987268,  0.78251622, -1.19755749, -0.40289447,
       -0.47437349, -0.18219004,  0.78257776,  0.62503069,  0.06096171,
       -0.62407909,  0.01908504, -1.30310535, -1.53060818, -0.16580024,
        1.66956665,  0.38528191,  0.77569736,  0.11827943, -1.06448968])

In [46]:
μ = 100 # If we have a mean of 100...
σ = 30 # ...and a standard deviation of 30...

#σ * np.random.randn(20) + μ # We can derive the unscaled values

#This is the same thing as the line above, because you can assign these array creation calls to a variable
σ * z_scores_iq + µ

array([136.45512259,  49.30381961, 123.47548671,  64.07327522,
        87.91316582,  85.76879517,  94.53429868, 123.4773328 ,
       118.7509206 , 101.82885125,  81.27762734, 100.57255126,
        60.90683942,  54.08175474,  95.02599276, 150.08699961,
       111.55845731, 123.27092095, 103.54838292,  68.0653096 ])

### `np.zeros`, `np.ones`, `np.full`

The `zeros` function provides the ability to create an array of a specified size full of `0`s: 

In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

The `ones` function does the same thing, but full of `1`s instead:

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

The `full` function allows you to specific a value:

In [50]:
#Here, you can tell it how long you want the array to be, as well as what value you want to repeat (length, value)
np.full(3, 17)

array([17, 17, 17])

We can also use these methods to create multi-dimensional arrays by passing a tuple of the dimensions of the desired array, instead of a single integer value.

In [51]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
np.full((3, 4), 17)

array([[17, 17, 17, 17],
       [17, 17, 17, 17],
       [17, 17, 17, 17]])

### `np.arange`

Numpy's `arange` function is very similar to python's built-in `range` function. It can take a single argument and generate a range from zero up to, but not including, the passed number.

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

We can also specify a starting point for the range:

In [55]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

As well as a step:

In [56]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

Unlike python's builtin `range`, numpy's `arange` can handle decimal numbers

In [57]:
np.arange(3, 5, 0.5)

array([3. , 3.5, 4. , 4.5])

### `np.linspace`

The `linspace` method creates a range of numbers between a minimum and a maximum, with a set number of elements.

In [58]:
# min: 1, max: 10, length: 4
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [59]:
# min: 1, max: 10, length: 7
np.linspace(1, 10, 7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

> Note: Here the maximum is **inclusive**
## Array Methods

Numpy arrays also come with built-in methods to make many mathematical operations easier.

Some of the most common are:

### `.min`

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [60]:
a.min()

1

### `.max`

In [61]:
a.max()

3

### `.mean`

In [62]:
a.mean()

2.0

### `.sum`

In [63]:
a.sum()

6

### `.std()`

In [64]:
a.std()

0.816496580927726

# Exercises!

In your numpy-pandas-visualization-exercises repo, create a file named `numpy_exercises.py` for this exercise.

Use the following code for the questions below:

In [ ]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

2. How many positive numbers are there?

3. How many even positive numbers are there?

4. If you were to add 3 to each data point, how many positive numbers would there be?

5. If you squared each number, what would the new mean and standard deviation be?

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See [this link](https://www.theanalysisfactor.com/centering-and-standardizing-predictors/) for more on centering.

7. Calculate the z-score for each data point. 

8. Copy the setup and exercise directions from [More Numpy Practice](https://gist.github.com/ryanorsinger/c4cf5a64ec33c014ff2e56951bc8a42d) into your `numpy_exercises.py` and add your solutions.

**Awesome Bonus** For much more practice with numpy, Go to https://github.com/rougier/numpy-100 and clone the repo down to your laptop. To clone a repository: - Copy the SSH address of the repository - cd ~/codeup-data-science - Then type `git clone git@github.com:rougier/numpy-100.git` - Now do `cd numpy-100` on your terminal. - Type `git remote remove origin`, so you won't accidentally try to push your work to Rougier's repo.

Congratulations! You have cloned Rougier's 100 numpy exercises to your computer. Now you need to make a new, blank, repository on GitHub.

Go to https://github.com/new to make a new repo. Name it numpy-100.
DO NOT check any check boxes. We need a blank, empty repo.
Finally, follow the directions to "push an existing repository from the command line" so that you can push up your changes to your own account.

Now do work, add it, commit it, and push it!